djangoProject/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from userextend.forms import AuthenticationNewForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('intro.urls')),
    path('', include('home.urls')),
    path('', include('student.urls')),
    path('', include('trainer.urls')),
    path('', include('feedback.urls')),
    path("login/", views.LoginView.as_view(form_class=AuthenticationNewForm), name="login"),
    path('', include('django.contrib.auth.urls')),
    path('', include('userextend.urls')),
]

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path("", views.HomeTemplateView.as_view(), name="home"),
]

student/urls.py
from django.urls import path

from student import views

urlpatterns = [
    path('create_student/', views.StudentCreateView.as_view(), name='create-student'),
    path('students_list/', views.StudentListView.as_view(), name='students-list'),
    path('update_student/<int:pk>/', views.StudentUpdateView.as_view(), name='update-student'),
    path('delete_student/<int:pk>/', views.StudentDeleteView.as_view(), name='delete-student'),
    path('students_detail/<int:pk>/', views.StudentDetailView.as_view(), name='students-detail'),
    path('student_history/', views.HistoryStudentListView.as_view(), name='student-history'),
]

student/models.py
from django.contrib.auth.models import User
from django.db import models
from trainer.models import Trainer


class Student(models.Model):
    gender_options = {
        ('M', 'Male'),
        ('F', 'Female'),
    }

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    age = models.PositiveIntegerField()
    email = models.EmailField(max_length=50)
    description = models.TextField(max_length=500)
    active = models.BooleanField(default=True)
    start_date = models.DateField()
    end_date = models.DateField()
    gender = models.CharField(max_length=1, choices=gender_options)
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE, null=True)

    created_at = models.DateTimeField(
        auto_now_add=True)  # stocam data si ora la salvarea unui student. Nu se mai modifica data si ora
    updated_at = models.DateTimeField(auto_now=True)  # stocam data si ora la orice modificare in clasa student

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=50)
    published_date = models.DateField()
    isbn = models.CharField(max_length=13)
    price = models.IntegerField(null=True)


class HistoryStudent(models.Model):
    message = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.message

trainer/models.py
from django.db import models


class Trainer(models.Model):

    department_choice = {
        ("b", 'Backend'),
        ("f", 'Frontend'),
        ("n", 'Network'),
    }

    first_name = models.CharField(max_length=20)
    last_name = models.CharField(max_length=20)
    course_name = models.CharField(max_length=40)
    email = models.EmailField(max_length=40)
    active = models.BooleanField(default=True)
    department = models.CharField(max_length=20, choices=department_choice, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

student/forms.py
from django import forms

from student.models import Student


class StudentForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
            'age': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Age'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description', 'rows': 3}),
            'start_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'end_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'gender': forms.Select(attrs={'class': 'form-select'}),
            'trainer': forms.Select(attrs={'class': 'form-select'}),
        }

    # Metoda clean este folosita pentru a verifica corectitudinea datelor introduse. Atunci cand implmmentam un formular
    # trebuie sa realizam validari personalizate care sa se aplice pe intregul formular

    def clean(self):
        cleaned_data = super().clean()

        # O validare prin care verificam unicitatea adresei de email. Daca am student cu o adresa de email sa nu pot adauga un alt student cu aceeasi de email
        get_email = cleaned_data.get('email')  # accesam valoarea cheii email din dictionarul cleaned_data
        check_emails = Student.objects.filter(
            email=get_email)  # interogam tabela student_student cautand in coloana email daca exista adresa de email stocata in variabila get_email
        if check_emails:  # verificam daca exista vreun student cu aceeasi adresa de email stocata in tabela
            msg = 'Email already registered'  # mesajul ce va afisat pe ecran
            self.add_error('email', msg)  # adaugarea erorii pe campul email cu mesajul stocat in variabiala msg.

        # O validare in care verificati daca start_date este mai mare decat end_date sa nu il lasati pe utilizator sa salveze inregistrarea

        start_date = cleaned_data.get('start_date')
        end_date = cleaned_data.get('end_date')
        if start_date > end_date:
            msg = 'Start date must be before end date'
            self.add_error('start_date', msg)

        # O validare in care sa verificati daca exista un student in baza de date cu acelasi first_name SI last_name.

        first_name = cleaned_data.get('first_name')
        last_name = cleaned_data.get('last_name')
        check_first_and_last_name = Student.objects.filter(first_name=first_name, last_name=last_name)
        if check_first_and_last_name:
            msg = 'The first and last name are already registered'
            self.add_error('first_name', msg)

        return cleaned_data


class StudentUpdateForm(forms.ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

        widgets = {
            'first_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'First Name'}),
            'last_name': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Last Name'}),
            'age': forms.NumberInput(attrs={'class': 'form-control', 'placeholder': 'Age'}),
            'email': forms.EmailInput(attrs={'class': 'form-control', 'placeholder': 'Email'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'placeholder': 'Description', 'rows': 3}),
            'start_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'end_date': forms.DateInput(attrs={'class': 'form-control', 'type': 'date'}),
            'gender': forms.Select(attrs={'class': 'form-select'}),
            'trainer': forms.Select(attrs={'class': 'form-select'}),
        }

student/views.py
import datetime
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.contrib.auth.models import User
from django.core.mail import EmailMessage
from django.template.loader import get_template
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, DeleteView, DetailView
from djangoProject.settings import EMAIL_HOST_USER
from student.filters import StudentFilter
from student.forms import StudentForm, StudentUpdateForm
from student.models import Student, HistoryStudent
from trainer.models import Trainer


class StudentCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = 'student/create_student.html'
    model = Student
    form_class = StudentForm
    success_url = reverse_lazy('home')
    permission_required = 'student.add_student'

    def form_valid(self, form):
        if form.is_valid():
            new_student = form.save()
            details_student = {
                'fullname': f'{new_student.first_name} {new_student.last_name}',
            }

            subject = 'Confirmare cont nou!'
            message = get_template('mail.html').render(details_student)
            mail = EmailMessage(subject, message, EMAIL_HOST_USER, [new_student.email])
            mail.content_subtype = 'html'
            mail.send()

            history_message = (f"Studentul,{new_student.last_name},{new_student.last_name},"
                               f"a fost create de {self.request.user.username} la data de:{datetime.date.today()}")

            HistoryStudent.objects.create(message=history_message, created_at=datetime.datetime.now(),
                                          user=User.objects.get(id=self.request.user.id), active=True)

        return super().form_valid(form)


class StudentListView(LoginRequiredMixin, PermissionRequiredMixin, ListView):
    template_name = 'student/list_of_students.html'
    model = Student
    context_object_name = "all_students"
    permission_required = 'student.can_view_list_of_students'

    def get_queryset(self):
        return Student.objects.filter(active=True)

    def get_context_data(self, **kwargs):
        context = super().get_context_data()

        students = Student.objects.filter(active=True)
        my_filters = StudentFilter(self.request.GET, queryset=students)
        context['all_students'] = my_filters.qs
        context['form_filters'] = my_filters.form

        return context


class StudentUpdateView(LoginRequiredMixin, PermissionRequiredMixin, UpdateView):
    template_name = 'student/update_student.html'
    model = Student
    form_class = StudentUpdateForm
    success_url = reverse_lazy('students-list')
    permission_required = 'student.change_student'


class StudentDeleteView(LoginRequiredMixin, PermissionRequiredMixin, DeleteView):
    template_name = "student/delete_student.html"
    model = Student
    success_url = reverse_lazy('students-list')
    permission_required = 'student.delete_student'


class StudentDetailView(LoginRequiredMixin, PermissionRequiredMixin, DetailView):
    template_name = "student/details_student.html"
    model = Student
    permission_required = 'student.view_student'


    # Metoda get_context_data este folosita in clasele de view cum ar fi DetailView, CreateView, DeleteView, ListView, TemplateView etc.
    # Aceasta metoda este folosita pentru a furniza date suplimentare catre template-ul asociat view-lui.

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        now = datetime.datetime.now()
        context['current_datetime'] = now

        context['students'] = Student.objects.all()
        context['trainers'] = Trainer.objects.all()

        print(context)

        return context


class HistoryStudentListView(ListView):
    model = HistoryStudent
    template_name = 'student/history_student.html'
    context_object_name = 'history_list'

    def get_queryset(self):
        return HistoryStudent.objects.filter(user=User.objects.get(id=self.request.user.id))

templates/student/create_student.html
{% extends 'base.html' %}

{% block title %} Create a new student {% endblock %}


{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Create a new student</h3>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-outline-success">Save</button>
                        </div>
                    </form>
                </div>
                
            </div>
        </div>
    </div>



{% endblock %}

templates/student/delete_student.html
{% extends 'base.html' %}

{% block title %} {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Delete student</h3>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="card-body">
                            <p>Are you sure you want to delete {{ student }}?</p>
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-outline-danger">Yes</button>
                            <a href="{% url "students-list" %}" class="btn btn-outline-secondary">No</a>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>

{% endblock %}

templates/student/details_student.html
{% extends 'base.html' %}

{% block title %} Details - {{ student }} {% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card text-center">
                    <div class="card-header">
                        View details
                    </div>
                    <div class="card-body">
                        <h5 class="card-title">{{ student }}t</h5>
                        <p class="card-text"> Email:{{ student.email }}</p>
                        <a href="{% url 'students-list' %}" class="btn btn-primary">Back</a>
                    </div>
                    <div class="card-footer text-body-secondary">
                        Created at: {{ student.created_at|date:'d-m-Y H:i:s' }} | Updated at:{{ student.updated_at|date:'d-m-Y H:i:s' }}
                    </div>
                </div>
            </div>
             </div>
        <br><br>
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <h3>List of students</h3>
                <table class="table">
                    <thead>
                            <tr>
                                <th>Fullnane</th>
                                <th>Email</th>
                                <th>Actions</th>
                            </tr>
                    </thead>
                    <tbody>
                        {% for student in students %}
                            <tr>
                                <td>{{ student }}</td>
                                <td>{{ student.email }}</td>
                                <td><a href="{% url 'students-detail' student.id %}" class="btn btn-outline-secondary">View details</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
        <br>
         <div class="row">
            <div class="col-md-6 offset-md-3">
                <h3>List of trainers</h3>
                <table class="table">
                    <thead>
                            <tr>
                                <th>Fullnane</th>
                                <th>Email</th>
                                <th>Actions</th>
                            </tr>
                    </thead>
                    <tbody>
                        {% for trainer in trainers %}
                            <tr>
                                <td>{{ trainer }}</td>
                                <td>{{ trainer.email }}</td>
                                <td><a href="{% url 'trainer-detail' trainer.id %}" class="btn btn-outline-secondary">View details</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>

{% endblock %}

templates/student/history_student.html
{% extends "base.html" %}

{% block title %}Student's History{% endblock %}

{% block content %}
    <h2>Student History</h2>
    <table class="table">
        <thead>
        <tr>
            <th>Message</th>
            <th>Created At</th>
            <th>Active</th>
            <th>User</th>
        </tr>
        </thead>
        <tbody>
        {% for history in history_list %}
            <tr>
                <td>{{ history.message }}</td>
                <td>{{ history.created_at }}</td>
                <td>{{ history.active }}</td>
                <td>{{ history.user.username }}</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock %}

templates/student/list_of_students.html
{% extends 'base.html' %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-2">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">
                            Filters
                        </h3>
                    </div>
                    <form method="get">
                        <div class="card-body">
                            {{ form_filters.as_p }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-outline-success">Login</button>
                            <a href="{% url 'students-list' %}" class="btn btn-outline-danger">Reset</a>
                        </div>
                    </form>
                </div>
            </div>
            <div class="col-md 10">
                {% if all_students %}
                    <h2>List of Students</h2>
                    <table class="table">
                        <thead>
                        <tr>
                            <th>First Name</th>
                            <th>Last Name</th>
                            <th>Age</th>
                            <th>Active</th>
                            <th>Start Date</th>
                            <th>End Date</th>
                            <th>Gender</th>
                            <th>Created At</th>
                            <th>Name of Trainer</th>
                            <th>Course Name</th>
                            <th>Trainer Department</th>
                            <th>Actions</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for student in all_students %}
                            <tr>
                                <td>{{ student.first_name }}</td>
                                <td>{{ student.last_name }}</td>
                                <td>{{ student.age }}</td>
                                <td>
                                    {% if student.active %}Yes{% else %}No{{% endif %}
                                </td>
                                <td>{{ student.start_date|date:'d-m-Y' }}</td>
                                <td>{{ student.end_date|date:'d-m-Y' }}</td>
                                <td>{{ student.get_gender_display }}</td>
                                <td>{{ student.created_at|date:"d-m-Y H:i:s" }}</td>

                                <td>{% if student.trainer %}
                                    {{ student.trainer }}
                                {% else %}
                                    No trainer
                                {% endif %}
                                </td>
                                <td>
                                    {% if student.trainer.course_name %}
                                        {{ student.trainer.course_name }}
                                    {% else %}
                                        No course
                                    {% endif %}
                                </td>
                                <td>
                                    {% if student.trainer.department %}
                                        {{ student.trainer.get_department_display }}
                                    {% else %}
                                        No department
                                    {% endif %}
                                </td>
                                <td>
                                    {% if perms.student.change_student or perms.student.delete_student or perms.student.view_student %}
                                        <div class="dropdown">
                                            <button class="btn btn-secondary dropdown-toggle" type="button"
                                                    data-bs-toggle="dropdown" aria-expanded="false">
                                                More Actions
                                            </button>
                                            <ul class="dropdown-menu">
                                                {% if perms.student.change_student %}
                                                    <li><a class="dropdown-item"
                                                           href="{% url 'update-student' student.id %}">Update</a></li>
                                                {% endif %}
                                                {% if perms.student.delete_student %}
                                                    <li><a class="dropdown-item"
                                                           href="{% url 'delete-student' student.id %}">Delete</a></li>
                                                {% endif %}
                                                {% if perms.student.view_student %}
                                                    <li><a class="dropdown-item"
                                                           href="{% url 'details-student' student.id %}">View
                                                        details</a>
                                                    </li>
                                                {% endif %}
                                            </ul>
                                        </div>
                                    {% else %}
                                        <p>No actions</p>
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                {% else %}
                    <div>
                        <h3 class="text-center">No data available</h3>
                    </div>
                {% endif %}
            </div>
        </div>
    </div>

{% endblock %}

templates/student/update_student.html
{% extends "base.html" %}
{% block title %}
    Update Student
{% endblock %}

{% block content %}
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6 offset-md-3">
                <div class="card">
                    <div class="card-header">
                        <h3 class="text-center">Update Student {{ student }}</h3>
                    </div>
                    <form method="post">
                        {% csrf_token %}
                        <div class="card-body">
                            {{ form }}
                        </div>
                        <div class="card-footer text-center">
                            <button type="submit" class="btn btn-outline-success">
                                Update
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}