djangoProject/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from userextend.forms import AuthenticationNewForm

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('intro.urls')),
    path('', include('home.urls')),
    path('', include('student.urls')),
    path('', include('trainer.urls')),
    path('', include('feedback.urls')),
    path("login/", views.LoginView.as_view(form_class=AuthenticationNewForm), name="login"),
    path('', include('django.contrib.auth.urls')),
    path('', include('userextend.urls')),
]

home/urls.py
from django.urls import path

from home import views

urlpatterns = [
    path("", views.HomeTemplateView.as_view(), name="home"),
]

student/models.py
from django.contrib.auth.models import User
from django.db import models
from trainer.models import Trainer


class Student(models.Model):
    gender_options = {
        ('M', 'Male'),
        ('F', 'Female'),
    }

    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    age = models.PositiveIntegerField()
    email = models.EmailField(max_length=50)
    description = models.TextField(max_length=500)
    active = models.BooleanField(default=True)
    start_date = models.DateField()
    end_date = models.DateField()
    gender = models.CharField(max_length=1, choices=gender_options)
    trainer = models.ForeignKey(Trainer, on_delete=models.CASCADE, null=True)

    created_at = models.DateTimeField(
        auto_now_add=True)  # stocam data si ora la salvarea unui student. Nu se mai modifica data si ora
    updated_at = models.DateTimeField(auto_now=True)  # stocam data si ora la orice modificare in clasa student

    def __str__(self):
        return f'{self.first_name} {self.last_name}'


class Book(models.Model):
    title = models.CharField(max_length=100)
    author = models.CharField(max_length=50)
    published_date = models.DateField()
    isbn = models.CharField(max_length=13)
    price = models.IntegerField(null=True)


class HistoryStudent(models.Model):
    message = models.TextField(max_length=500)
    created_at = models.DateTimeField(auto_now_add=True)
    active = models.BooleanField(default=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return self.message

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{% block title %} {% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/my_style.css' %}">
</head>
<body>

{% include 'navbar.html'%}
{% block content %} {% endblock %}

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>

</body>
</html>

templates/mail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
<div style="font-family: Arial, sans-serif; max-width: 600px; margin: 0 auto; padding: 20px;">
    <h2 style="color: #333;">Confirmare Creare Cont</h2>
    <p>Bună {{ fullname }},</p>
    <p>Te felicităm! Contul tău a fost creat cu succes.</p>
    <p>Ai acum acces la toate funcțiile platformei noastre.</p>
    <p>Pentru a începe să te bucuri de serviciile noastre, te rugăm să te autentifici cu username-ul
        <strong>{{ username }}</strong>.</p>
    <p>Pentru a accesa aplicația noastră, te rugăm să apeși pe următorul link:</p>
    <p><a href="http://127.0.0.1:8000/login/" style="color: #007bff;">Accesează aplicația</a></p>
    <p>Mulțumim că ai ales să faci parte din comunitatea noastră!</p>
    <br>
    <p>Cu respect,</p>
    <p>Echipa RO59</p>
</div>
</body>
</html>

templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Project</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="{% url 'data' %}">Data extract</a>
                </li>
                {% if user.is_authenticated %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Intro
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'list-cars' %}">List of Cars</a></li>
                            <li><a class="dropdown-item" href="{% url 'list-phones' %}">List of Phones</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Student
                        </a>
                        <ul class="dropdown-menu">
                            {% if perms.app_label.codename %}{% endif %}
                            {% if perms.student.add_student %}
                                <li><a class="dropdown-item" href="{% url 'create-student' %}">Create a new student</a>
                                </li>
                            {% endif %}
                            {% if perms.student.can_view_list_of_students %}
                                <li><a class="dropdown-item" href="{% url 'students-list' %}">List of Students</a></li>
                            {% endif %}
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Trainer
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'create-trainer' %}">Create a new Trainer</a></li>
                            <li><a class="dropdown-item" href="{% url 'trainer-list' %}">List of Trainer</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Feedback
                        </a>
                        <ul class="dropdown-menu">
                            <li><a class="dropdown-item" href="{% url 'create-feedback' %}">Write a feedback</a></li>
                            <li><a class="dropdown-item" href="{% url 'list-of-feedbacks' %}">List of Feedbacks</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Students
                        </a>
                        <ul class="dropdown-menu">
                            {% for stud in students %}
                                <li><a class="dropdown-item" href="{% url 'students-detail' stud.id %}">{{ stud }}</a>
                                </li>
                            {% endfor %}
                            <li><a class="dropdown-item" href="{% url 'student-history' %}">Student's History</a></li>
                        </ul>
                    </li>
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                           aria-expanded="false">
                            Trainers
                        </a>
                        <ul class="dropdown-menu">
                            {% for trainer in trainers %}
                                <li><a class="dropdown-item"
                                       href="{% url 'get-all-students' trainer.id %}">{{ trainer }}</a></li>
                            {% endfor %}
                        </ul>
                    </li>

                {% endif %}
            </ul>
            {% if user.is_authenticated %}
                <form method="post" action="{% url 'logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-outline-secondary">Logout, {{ user.username }}</button>
                </form>

            {% else %}
                <div>
                    <a href="{% url 'login' %}" class="btn btn-outline-secondary">Login</a>
                    <a href="{% url 'create-user' %}" class="btn btn-outline-success">Sign Up</a>
                </div>
            {% endif %}
            <form class="d-flex" role="search">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>